FROM node:alpine

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get install -y nodejs

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
